FROM node:20-alpine AS base
RUN apk add --no-cache libc6-compat

# Install dependencies
FROM base AS deps
WORKDIR /app
COPY package.json ./
COPY package-lock.json* ./
RUN npm ci

# Build
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build-time env vars needed for Next.js NEXT_PUBLIC_* inlining
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_CALCOM_URL
ARG SUPABASE_SERVICE_ROLE_KEY
ARG SUPABASE_JWT_SECRET
ARG ANTHROPIC_API_KEY
ARG CLAUDE_SONNET_MODEL
ARG CLAUDE_HAIKU_MODEL
ARG STRIPE_SECRET_KEY
ARG STRIPE_WEBHOOK_SECRET
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG RESEND_FROM_NAME
ARG N8N_BASE_URL
ARG N8N_API_KEY
ARG N8N_WEBHOOK_BASE
ARG NTFY_TOPIC_URL
ARG DOCUSEAL_API_KEY

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_CALCOM_URL=$NEXT_PUBLIC_CALCOM_URL
ENV NEXT_TELEMETRY_DISABLED=1

# Write .env.production for build-time page data collection
RUN printf "SUPABASE_SERVICE_ROLE_KEY=%s\nSUPABASE_JWT_SECRET=%s\nANTHROPIC_API_KEY=%s\nCLAUDE_SONNET_MODEL=%s\nCLAUDE_HAIKU_MODEL=%s\nSTRIPE_SECRET_KEY=%s\nSTRIPE_WEBHOOK_SECRET=%s\nRESEND_API_KEY=%s\nRESEND_FROM_EMAIL=%s\nRESEND_FROM_NAME=%s\nN8N_BASE_URL=%s\nN8N_API_KEY=%s\nN8N_WEBHOOK_BASE=%s\nNTFY_TOPIC_URL=%s\nDOCUSEAL_API_KEY=%s\nNEXT_PUBLIC_APP_URL=%s\nNEXT_PUBLIC_SUPABASE_URL=%s\nNEXT_PUBLIC_SUPABASE_ANON_KEY=%s\nNEXT_PUBLIC_CALCOM_URL=%s\n" \
  "$SUPABASE_SERVICE_ROLE_KEY" "$SUPABASE_JWT_SECRET" "$ANTHROPIC_API_KEY" "$CLAUDE_SONNET_MODEL" "$CLAUDE_HAIKU_MODEL" "$STRIPE_SECRET_KEY" "$STRIPE_WEBHOOK_SECRET" "$RESEND_API_KEY" "$RESEND_FROM_EMAIL" "$RESEND_FROM_NAME" "$N8N_BASE_URL" "$N8N_API_KEY" "$N8N_WEBHOOK_BASE" "$NTFY_TOPIC_URL" "$DOCUSEAL_API_KEY" "$NEXT_PUBLIC_APP_URL" "$NEXT_PUBLIC_SUPABASE_URL" "$NEXT_PUBLIC_SUPABASE_ANON_KEY" "$NEXT_PUBLIC_CALCOM_URL" \
  > .env.production

RUN npm run build

# Production
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

RUN mkdir .next
RUN chown nextjs:nodejs .next

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy .env.production for runtime
COPY --from=builder --chown=nextjs:nodejs /app/.env.production ./.env.production

USER nextjs

EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
